In [4]:
from collections import defaultdict, deque

class GrafoResidual:
    def __init__(self, grafo):
        self.grafo = grafo
        self.residual = defaultdict(dict)

    def adiciona_aresta_residual(self, u, v, capacidade):
        self.residual[u][v] = capacidade
        self.residual[v][u] = 0

def ford_fulkerson(grafo, source, sink):
    grafo_residual = GrafoResidual(grafo)

    while True:
        caminho_aumento = encontra_caminho_aumento(grafo_residual, source, sink)
        
        if not caminho_aumento:
            break

        fluxo_aumento = min(grafo_residual.residual[u][v] for u, v in caminho_aumento)
        
        for u, v in caminho_aumento:
            grafo_residual.residual[u][v] -= fluxo_aumento
            grafo_residual.residual[v][u] += fluxo_aumento

    fluxo_maximo = sum(grafo_residual.residual[source][v] for v in grafo_residual.residual[source])
    return fluxo_maximo

def encontra_caminho_aumento(grafo_residual, source, sink):
    visitado = set()
    fila = deque([(source, [source])])

    while fila:
        u, caminho = fila.popleft()

        for v, capacidade_residual in grafo_residual.residual[u].items():
            if capacidade_residual > 0 and v not in visitado:
                visitado.add(v)
                novo_caminho = caminho + [v]

                if v == sink:
                    return novo_caminho

                fila.append((v, novo_caminho))

    return None

# Exemplo de uso:
grafo = {
    'S': {'A': 6, 'B': 12},
    'A': {'S': 0, 'C': 8},
    'B': {'S': 0, 'C': 3, 'D': 5},
    'C': {'A': 0, 'B': 0, 'T': 14},
    'D': {'B': 0, 'T': 7},
    'T': {'C': 0, 'D': 0}
}

source = 'S'
sink = 'T'

fluxo_maximo = ford_fulkerson(grafo, source, sink)
print(f"O fluxo máximo de {source} para {sink} é: {fluxo_maximo}")

O fluxo máximo de S para T é: 0


In [6]:
import numpy as np

grafo = {
    'S': {'A': 6, 'B': 12},
    'A': {'S': 0, 'C': 8},
    'B': {'S': 0, 'C': 3, 'D': 5},
    'C': {'A': 0, 'B': 0, 'T': 14},
    'D': {'B': 0, 'T': 7},
    'T': {'C': 0, 'D': 0}
}

# Obter a lista de vértices ordenados
vertices = sorted(set(vertice for origem, destinos in grafo.items() for vertice in [origem] + list(destinos.keys())))

# Criar a matriz de adjacência
matriz_adjacencia = np.zeros((len(vertices), len(vertices)), dtype=int)

for i, origem in enumerate(vertices):
    for j, destino in enumerate(vertices):
        if origem in grafo and destino in grafo[origem]:
            matriz_adjacencia[i, j] = grafo[origem][destino]

# Exibir a matriz de adjacência
print("Matriz de Adjacência:")
print(matriz_adjacencia)


Matriz de Adjacência:
[[ 0  0  8  0  0  0]
 [ 0  0  3  5  0  0]
 [ 0  0  0  0  0 14]
 [ 0  0  0  0  0  7]
 [ 6 12  0  0  0  0]
 [ 0  0  0  0  0  0]]


In [5]:
class Grafo:
    def __init__(self, grafo):
        self.grafo = grafo
        self.ROW = len(grafo)

    def BFS(self, s, t, parent):
        visitado = [False] * (self.ROW)
        fila = []
        fila.append(s)
        visitado[s] = True

        while fila:
            u = fila.pop(0)

            for ind, val in enumerate(self.grafo[u]):
                if not visitado[ind] and val > 0:
                    fila.append(ind)
                    visitado[ind] = True
                    parent[ind] = u
                    if ind == t:
                        return True
        return False

    def FordFulkerson(self, origem, destino):
        parent = [-1] * (self.ROW)
        fluxo_maximo = 0 

        while self.BFS(origem, destino, parent):
            fluxo_caminho = float("Inf")
            s = destino
            
            while s != origem:
                fluxo_caminho = min(fluxo_caminho, self.grafo[parent[s]][s])
                s = parent[s]

            fluxo_maximo += fluxo_caminho
            v = destino
            
            while v != origem:
                u = parent[v]
                self.grafo[u][v] -= fluxo_caminho
                self.grafo[v][u] += fluxo_caminho
                v = parent[v]

        return fluxo_maximo


grafo = [
    [0, 6, 12, 0, 0, 0],
    [0, 0, 0, 8, 0, 0],
    [0, 0, 0, 3, 5, 0],
    [0, 0, 0, 0, 0, 14],
    [0, 0, 0, 0, 0, 7],
    [0, 0, 0, 0, 0, 0]
]

g = Grafo(grafo)

origem = 0
destino = 5

print("O fluxo máximo possível é %d " % g.FordFulkerson(origem, destino))

O fluxo máximo possível é 14 
